'use client';

import { useEffect, useState } from 'react';
import {
  useM3Store,
  AFFIDAVIT_EXPENSE_CATEGORIES,
  CATEGORY_LABELS,
  LINE_ITEM_LABELS,
} from '@/src/stores/m3Store';

// ─── Brand tokens ─────────────────────────────────────────────────────────────
const NAVY = '#1B2A4A';
const GOLD = '#C8A96E';
const WHITE = '#FFFFFF';
const RED = '#C0392B';
const SOURCE = '"Source Sans Pro", -apple-system, system-ui, sans-serif';
const PLAYFAIR = '"Playfair Display", Georgia, serif';

// ─── Currency formatting (always 2-decimal in print for legal consistency) ───
function formatCurrency(amount) {
  const v = Number(amount) || 0;
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(v);
}

const DISCLAIMER_TEXT =
  'EDUCATIONAL TOOL — NOT A LEGAL DOCUMENT. This summary was generated by ClearPath for Women for educational and planning purposes only. A Financial Affidavit is a sworn legal document that must be prepared and filed by your attorney.';

// ─── Disclaimer band (top/bottom) ────────────────────────────────────────────
function DisclaimerBand() {
  return (
    <div
      role="note"
      aria-label="Educational tool disclaimer"
      style={{
        backgroundColor: RED,
        color: WHITE,
        fontFamily: SOURCE,
        fontSize: 12,
        fontWeight: 600,
        padding: '12px 16px',
        lineHeight: 1.45,
        borderRadius: 4,
      }}
    >
      {DISCLAIMER_TEXT}
    </div>
  );
}

export default function AffidavitPrintPage() {
  const affidavitBuilder = useM3Store((s) => s.affidavitBuilder);

  const [hydrated, setHydrated] = useState(false);
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setHydrated(true);
  }, []);

  if (!hydrated) {
    return (
      <div
        style={{
          padding: 32,
          fontFamily: SOURCE,
          color: NAVY,
          minHeight: '100vh',
          backgroundColor: WHITE,
        }}
      >
        Loading…
      </div>
    );
  }

  const { sections, progress, prePopulated, completedAt } = affidavitBuilder;
  const { income, expenses, assets, liabilities } = sections;

  const totalAssets = assets.summary?.totalAssets || 0;
  const totalLiabilities = liabilities.summary?.totalLiabilities || 0;
  const netWorth = totalAssets - totalLiabilities;

  return (
    <>
      <style>{`
        @page {
          size: letter;
          margin: 0.75in;
        }
        @media print {
          body {
            -webkit-print-color-adjust: exact;
            print-color-adjust: exact;
            background-color: #FFFFFF !important;
          }
          .no-print {
            display: none !important;
          }
          .print-page-break {
            page-break-before: always;
            break-before: page;
          }
          .avoid-break {
            page-break-inside: avoid;
            break-inside: avoid;
          }
          main {
            background-color: #FFFFFF !important;
            padding: 0 !important;
          }
        }
        @media screen {
          .page-shell {
            max-width: 8.5in;
            min-height: 11in;
            margin: 24px auto;
            padding: 0.75in;
            background-color: #FFFFFF;
            box-shadow: 0 4px 18px rgba(0,0,0,0.08);
          }
        }
      `}</style>
      <main
        style={{
          backgroundColor: '#EEEEEE',
          minHeight: '100vh',
          fontFamily: SOURCE,
          color: NAVY,
        }}
      >
        <div className="page-shell">
          {/* Top disclaimer */}
          <DisclaimerBand />

          {/* Print button */}
          <div
            className="no-print"
            style={{ marginTop: 14, marginBottom: 14, textAlign: 'right' }}
          >
            <button
              type="button"
              onClick={() => window.print()}
              style={{
                padding: '10px 20px',
                backgroundColor: NAVY,
                color: WHITE,
                fontFamily: SOURCE,
                fontWeight: 600,
                fontSize: 13,
                border: 'none',
                borderRadius: 6,
                cursor: 'pointer',
              }}
            >
              Print
            </button>
          </div>

          {/* Title */}
          <header style={{ marginTop: 20, marginBottom: 18, textAlign: 'center' }}>
            <h1
              style={{
                fontFamily: PLAYFAIR,
                fontWeight: 700,
                fontSize: 26,
                color: NAVY,
                margin: 0,
                letterSpacing: 0.3,
              }}
            >
              Financial Affidavit — Educational Summary
            </h1>
            <p
              style={{
                fontFamily: SOURCE,
                fontSize: 12,
                color: NAVY,
                opacity: 0.75,
                margin: '6px 0 0',
              }}
            >
              Generated by ClearPath for Women
              {completedAt
                ? ` • ${new Date(completedAt).toLocaleDateString('en-US', {
                    year: 'numeric',
                    month: 'long',
                    day: 'numeric',
                  })}`
                : ''}
            </p>
          </header>

          {/* ─── Part A: Income ──────────────────────────────────────────── */}
          <section className="avoid-break" style={{ marginBottom: 28 }}>
            <SectionHeader letter="A" title="Income" complete={progress.incomeComplete} />

            {income.primaryEmployment?.employer && (
              <LabeledRow
                label="Employer"
                value={income.primaryEmployment.employer}
              />
            )}
            {income.primaryEmployment?.payFrequency && (
              <LabeledRow
                label="Pay Frequency"
                value={titleCase(income.primaryEmployment.payFrequency)}
              />
            )}
            {income.primaryEmployment?.paychecksPerYear ? (
              <LabeledRow
                label="Paychecks per Year"
                value={String(income.primaryEmployment.paychecksPerYear)}
              />
            ) : null}

            <PrintTable
              headers={['Item', 'Per Paycheck', 'Monthly']}
              rows={[
                [
                  'Gross Pay',
                  income.primaryEmployment?.grossPayPerCheck
                    ? formatCurrency(income.primaryEmployment.grossPayPerCheck)
                    : '—',
                  income.primaryEmployment?.grossMonthlyIncome
                    ? formatCurrency(income.primaryEmployment.grossMonthlyIncome)
                    : '—',
                ],
              ]}
            />

            {(income.primaryEmployment?.deductions || []).length > 0 && (
              <>
                <Subheader>Deductions</Subheader>
                <PrintTable
                  headers={['Deduction', 'Monthly']}
                  rows={income.primaryEmployment.deductions.map((d) => [
                    d.label + (d.isVoluntary ? ' (Voluntary)' : ''),
                    formatCurrency(d.monthly || 0),
                  ])}
                  totals={[
                    'Total Deductions (Monthly)',
                    formatCurrency(income.primaryEmployment.totalDeductions || 0),
                  ]}
                />
              </>
            )}

            <SummaryLine
              label="Net Monthly Income (after deductions)"
              value={formatCurrency(income.primaryEmployment?.netMonthlyIncome || 0)}
            />

            {(income.otherIncome || []).length > 0 && (
              <>
                <Subheader>Other Income Sources</Subheader>
                <PrintTable
                  headers={['Source', 'Monthly Amount', 'Taxable']}
                  rows={income.otherIncome.map((s) => [
                    s.source || '(Unnamed)',
                    formatCurrency(s.monthlyAmount || 0),
                    s.isTaxable ? 'Yes' : 'No',
                  ])}
                />
              </>
            )}

            {(income.deductionsFromOtherIncome || []).length > 0 && (
              <>
                <Subheader>Deductions from Other Income</Subheader>
                <PrintTable
                  headers={['Description', 'Monthly']}
                  rows={income.deductionsFromOtherIncome.map((d) => [
                    d.label || '—',
                    formatCurrency(d.monthlyAmount || 0),
                  ])}
                />
              </>
            )}

            <SummaryLine
              label="Net Monthly Income — All Sources"
              value={formatCurrency(income.netMonthlyIncomeAllSources || 0)}
              emphasis
            />
            <SummaryLine
              label="Monthly Income of Dependent Children"
              value={formatCurrency(income.monthlyIncomeOfDependentChildren || 0)}
            />
          </section>

          {/* ─── Part B: Expenses ────────────────────────────────────────── */}
          <section style={{ marginBottom: 28 }} className="print-page-break">
            <SectionHeader
              letter="B"
              title="Expenses"
              complete={progress.expensesComplete}
            />

            {AFFIDAVIT_EXPENSE_CATEGORIES.map((cat) => {
              const categoryObj = expenses[cat] || {};
              const fieldKeys = Object.keys(categoryObj);
              const subtotal = fieldKeys.reduce(
                (s, f) => s + (Number(categoryObj[f]) || 0),
                0
              );
              const rows = fieldKeys
                .filter((f) => Number(categoryObj[f]) > 0)
                .map((f) => [
                  LINE_ITEM_LABELS[f] || f,
                  formatCurrency(categoryObj[f]),
                  formatCurrency((Number(categoryObj[f]) || 0) * 12),
                ]);

              return (
                <div key={cat} className="avoid-break" style={{ marginBottom: 14 }}>
                  <Subheader>{CATEGORY_LABELS[cat]}</Subheader>
                  {rows.length > 0 ? (
                    <PrintTable
                      headers={['Line Item', 'Monthly', 'Annual']}
                      rows={rows}
                      totals={['Subtotal', formatCurrency(subtotal), formatCurrency(subtotal * 12)]}
                    />
                  ) : (
                    <p
                      style={{
                        fontFamily: SOURCE,
                        fontSize: 12,
                        color: NAVY,
                        opacity: 0.6,
                        fontStyle: 'italic',
                        margin: '4px 0 10px',
                      }}
                    >
                      No entries
                    </p>
                  )}
                </div>
              );
            })}

            <div
              className="avoid-break"
              style={{ marginTop: 16, borderTop: `2px solid ${GOLD}`, paddingTop: 8 }}
            >
              <SummaryLine
                label="Total Monthly Expenses (excluding children)"
                value={formatCurrency(expenses.totalMonthlyExpensesExcludingChildren || 0)}
              />
              <SummaryLine
                label="Total Monthly Expenses"
                value={formatCurrency(expenses.totalMonthlyExpenses || 0)}
                emphasis
              />
            </div>
          </section>

          {/* ─── Part C: Assets ──────────────────────────────────────────── */}
          <section className="avoid-break print-page-break" style={{ marginBottom: 28 }}>
            <SectionHeader letter="C" title="Assets" complete={progress.assetsComplete} />
            <PrintTable
              headers={['Category', 'Value']}
              rows={[
                ['Real Property', formatCurrency(assets.summary?.realProperty || 0)],
                ['Cash Accounts', formatCurrency(assets.summary?.cashAccounts || 0)],
                ['Investments', formatCurrency(assets.summary?.investments || 0)],
                [
                  'Retirement Accounts',
                  formatCurrency(assets.summary?.retirementAccounts || 0),
                ],
                ['Other Assets', formatCurrency(assets.summary?.otherAssets || 0)],
                [
                  'Personal Property',
                  formatCurrency(assets.summary?.personalProperty || 0),
                ],
              ]}
              totals={['Total Assets', formatCurrency(totalAssets)]}
            />
          </section>

          {/* ─── Part D: Liabilities ─────────────────────────────────────── */}
          <section className="avoid-break" style={{ marginBottom: 28 }}>
            <SectionHeader
              letter="D"
              title="Liabilities"
              complete={progress.liabilitiesComplete}
            />
            {liabilities.noLiabilitiesConfirmed ? (
              <p
                style={{
                  fontFamily: SOURCE,
                  fontSize: 13,
                  color: NAVY,
                  margin: '8px 0',
                }}
              >
                No liabilities confirmed.
              </p>
            ) : (
              <PrintTable
                headers={['Category', 'Balance']}
                rows={[
                  ['Loans', formatCurrency(liabilities.summary?.loans || 0)],
                  ['Credit Cards', formatCurrency(liabilities.summary?.creditCards || 0)],
                  ['Other Debt', formatCurrency(liabilities.summary?.otherDebt || 0)],
                ]}
                totals={['Total Liabilities', formatCurrency(totalLiabilities)]}
              />
            )}
          </section>

          {/* Net Worth */}
          <section className="avoid-break" style={{ marginBottom: 28 }}>
            <h2
              style={{
                fontFamily: PLAYFAIR,
                fontWeight: 700,
                fontSize: 18,
                color: NAVY,
                margin: '0 0 10px',
              }}
            >
              Net Worth
            </h2>
            <div style={{ maxWidth: 420 }}>
              <SummaryLine label="Total Assets" value={formatCurrency(totalAssets)} />
              <SummaryLine
                label="Total Liabilities"
                value={`(${formatCurrency(totalLiabilities)})`}
              />
              <div
                style={{
                  borderTop: `2px solid ${GOLD}`,
                  marginTop: 6,
                  paddingTop: 4,
                }}
              >
                <SummaryLine label="Net Worth" value={formatCurrency(netWorth)} emphasis />
              </div>
            </div>
          </section>

          {/* Pre-pop provenance footer */}
          <section
            className="avoid-break"
            style={{
              marginTop: 24,
              padding: '10px 14px',
              border: `1px solid #E8EBF0`,
              borderRadius: 4,
              fontFamily: SOURCE,
              fontSize: 11,
              color: NAVY,
              opacity: 0.7,
            }}
          >
            <strong style={{ fontWeight: 600 }}>Data Sources: </strong>
            {prePopulated.fromTool1
              ? 'Pay Stub Decoder (M3 Tool 1). '
              : ''}
            {prePopulated.fromTool2
              ? 'Budget Modeler (M3 Tool 2). '
              : ''}
            {prePopulated.fromM2
              ? 'Marital Estate Inventory (M2). '
              : ''}
            {!prePopulated.fromTool1 && !prePopulated.fromTool2 && !prePopulated.fromM2
              ? 'Manual entry only.'
              : ''}
          </section>

          {/* Bottom disclaimer */}
          <div style={{ marginTop: 28 }}>
            <DisclaimerBand />
          </div>
        </div>
      </main>
    </>
  );
}

// ─── Helpers & subcomponents ─────────────────────────────────────────────────
function titleCase(s) {
  if (!s) return '';
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function SectionHeader({ letter, title, complete }) {
  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: 10,
        marginBottom: 10,
        borderBottom: `2px solid ${NAVY}`,
        paddingBottom: 6,
      }}
    >
      <span
        style={{
          fontFamily: PLAYFAIR,
          fontWeight: 700,
          fontSize: 14,
          color: WHITE,
          backgroundColor: NAVY,
          padding: '2px 10px',
          borderRadius: 4,
        }}
      >
        PART {letter}
      </span>
      <h2
        style={{
          fontFamily: PLAYFAIR,
          fontWeight: 700,
          fontSize: 18,
          color: NAVY,
          margin: 0,
          flex: 1,
        }}
      >
        {title}
      </h2>
      {complete ? (
        <span style={{ fontFamily: SOURCE, fontSize: 11, color: '#2D8A4E', fontWeight: 600 }}>
          ✓ Complete
        </span>
      ) : (
        <span style={{ fontFamily: SOURCE, fontSize: 11, color: NAVY, opacity: 0.55 }}>
          In progress
        </span>
      )}
    </div>
  );
}

function Subheader({ children }) {
  return (
    <h3
      style={{
        fontFamily: PLAYFAIR,
        fontWeight: 700,
        fontSize: 14,
        color: NAVY,
        margin: '14px 0 6px',
      }}
    >
      {children}
    </h3>
  );
}

function LabeledRow({ label, value }) {
  return (
    <div
      style={{
        display: 'flex',
        justifyContent: 'space-between',
        padding: '4px 0',
        borderBottom: '1px solid #F0F2F5',
        fontFamily: SOURCE,
        fontSize: 12,
        color: NAVY,
      }}
    >
      <span style={{ opacity: 0.7 }}>{label}</span>
      <span style={{ fontWeight: 600 }}>{value}</span>
    </div>
  );
}

function SummaryLine({ label, value, emphasis = false }) {
  return (
    <div
      style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'baseline',
        padding: '4px 0',
        fontFamily: SOURCE,
        fontSize: emphasis ? 14 : 13,
        color: NAVY,
      }}
    >
      <span style={{ fontWeight: emphasis ? 700 : 500 }}>{label}</span>
      <span
        style={{
          fontFamily: PLAYFAIR,
          fontWeight: 700,
          fontSize: emphasis ? 16 : 14,
        }}
      >
        {value}
      </span>
    </div>
  );
}

function PrintTable({ headers, rows, totals }) {
  return (
    <table
      style={{
        width: '100%',
        borderCollapse: 'collapse',
        fontFamily: SOURCE,
        fontSize: 12,
        color: NAVY,
        marginTop: 4,
      }}
    >
      <thead>
        <tr>
          {headers.map((h, i) => (
            <th
              key={i}
              style={{
                textAlign: i === 0 ? 'left' : 'right',
                padding: '6px 8px 6px 0',
                fontWeight: 600,
                borderBottom: `1px solid ${NAVY}`,
                fontSize: 11,
                letterSpacing: 0.3,
                textTransform: 'uppercase',
              }}
            >
              {h}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.length === 0 ? (
          <tr>
            <td
              colSpan={headers.length}
              style={{
                padding: '8px 0',
                fontStyle: 'italic',
                opacity: 0.6,
              }}
            >
              No entries
            </td>
          </tr>
        ) : (
          rows.map((r, i) => (
            <tr key={i} style={{ borderBottom: '1px solid #F0F2F5' }}>
              {r.map((cell, j) => (
                <td
                  key={j}
                  style={{
                    padding: '5px 8px 5px 0',
                    textAlign: j === 0 ? 'left' : 'right',
                  }}
                >
                  {cell}
                </td>
              ))}
            </tr>
          ))
        )}
      </tbody>
      {totals && (
        <tfoot>
          <tr>
            {totals.map((cell, i) => (
              <td
                key={i}
                style={{
                  padding: '8px 8px 4px 0',
                  textAlign: i === 0 ? 'left' : 'right',
                  borderTop: `1px solid ${GOLD}`,
                  fontWeight: 700,
                }}
              >
                {cell}
              </td>
            ))}
            {totals.length < headers.length &&
              Array.from({ length: headers.length - totals.length }).map((_, i) => (
                <td
                  key={`fill-${i}`}
                  style={{
                    padding: '8px 8px 4px 0',
                    borderTop: `1px solid ${GOLD}`,
                  }}
                />
              ))}
          </tr>
        </tfoot>
      )}
    </table>
  );
}
